/**
 * Demo game metadata (no ROMs — users must upload their own).
 * These entries have isLocal: false and no romPath.
 */

import type { Game } from '../types'

export const DEMO_GAMES: Game[] = [
  {
    id: 'demo-nes-1',
    title: 'Upload Your NES ROM',
    console: 'nes',
    description: 'Play any NES game by uploading your own .nes ROM file. The emulator supports the full NES library.',
    thumbnailUrl: '',
    year: 1985,
    genre: ['Action', 'Platform'],
    players: 1,
    rating: 5,
    isLocal: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-snes-1',
    title: 'Upload Your SNES ROM',
    console: 'snes',
    description: 'Play any SNES game by uploading your own .sfc or .smc ROM file. Full Super Nintendo emulation.',
    thumbnailUrl: '',
    year: 1991,
    genre: ['Action', 'RPG'],
    players: 1,
    rating: 5,
    isLocal: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-gba-1',
    title: 'Upload Your GBA ROM',
    console: 'gameboy-advance',
    description: 'Play any Game Boy Advance game by uploading your own .gba ROM file.',
    thumbnailUrl: '',
    year: 2001,
    genre: ['Action', 'Adventure'],
    players: 1,
    rating: 5,
    isLocal: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-gb-1',
    title: 'Upload Your Game Boy ROM',
    console: 'gameboy',
    description: 'Play any original Game Boy game by uploading your own .gb ROM file.',
    thumbnailUrl: '',
    year: 1989,
    genre: ['Puzzle', 'Platform'],
    players: 1,
    rating: 5,
    isLocal: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-genesis-1',
    title: 'Upload Your Genesis ROM',
    console: 'sega-genesis',
    description: 'Play any Sega Genesis / Mega Drive game by uploading your .md, .bin, or .gen ROM file.',
    thumbnailUrl: '',
    year: 1990,
    genre: ['Action', 'Platform'],
    players: 1,
    rating: 5,
    isLocal: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'demo-gbc-1',
    title: 'Upload Your GBC ROM',
    console: 'gameboy-color',
    description: 'Play any Game Boy Color game by uploading your own .gbc ROM file.',
    thumbnailUrl: '',
    year: 1998,
    genre: ['RPG', 'Adventure'],
    players: 1,
    rating: 5,
    isLocal: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
